### PR TITLE
Include MIT license from original repository

### PR DESCRIPTION
**Pull request by Kukks**
This repository is forked from https://github.com/LunaNode/launchbtcpay which was created by @uakfdotb
As per MIT license, you MUST include the original license.

### CODE REVIEW

**Comment by MrNaif2018** [comment]
I have contacted lunanode support back then and sent them the link to the repo. They didn't have any issues with it. Will re-ask them if there is any but I doubt it. Thanks though. Closing but will reply with the result

**Comment by MrNaif2018** [comment]
As I thought, it is not required. Only the copyright owner can enforce the use of license if they want to.
Here's a proof:
изображение

**Comment by uakfdotb** [comment]
Sorry @Kukks, I did not mean to be rude in the ticket reply, did not expect it to be posted publicly, just intended to sympathize with MrNaif2018 a bit, but clearly it came out completely wrong. I appreciate your time and effort in opening this and similar tickets -- informing other users about license practices is constructive and helpful to the community. (also of course appreciate your work on btcpay!) In this particular case, since it is essentially free advertising for LunaNode, MrNaif2018 has permission to include whatever copyright notice he or she desires (which of course could include derivative works, which is fine for me too since the whole thing is built around LunaNode API).

**Comment by MrNaif2018** [comment]
Sorry for posting publicly, just wanted to show that I am not pretending or lying on anything, and to be completely transparent on such issues as license ones (:

Thanks for your clarification!

**Comment by Kukks** [comment]
That's all good then. I have no issue as long as it's handled correctly.

**Pull request closed without merging**
